// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOFo9W9qgK5nergzI6PnLyo5fNnCFlBpY',
    appId: '1:645043733402:web:580d4b0da51d2bcfd9f023',
    messagingSenderId: '645043733402',
    projectId: 'health-arch-4b7c7',
    authDomain: 'health-arch-4b7c7.firebaseapp.com',
    storageBucket: 'health-arch-4b7c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJWy3cNUpTvBBbM2LX2IIyHNhWytlO7yk',
    appId: '1:645043733402:android:473a3c4af5430f34d9f023',
    messagingSenderId: '645043733402',
    projectId: 'health-arch-4b7c7',
    storageBucket: 'health-arch-4b7c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUjv7a-BPm_KlO64TufWUuAw_4Z3urdSQ',
    appId: '1:645043733402:ios:6d239c23bd1f1204d9f023',
    messagingSenderId: '645043733402',
    projectId: 'health-arch-4b7c7',
    storageBucket: 'health-arch-4b7c7.appspot.com',
    iosClientId: '645043733402-e3dn9i5s56hhc3p1v34osj9me8e2vfcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUjv7a-BPm_KlO64TufWUuAw_4Z3urdSQ',
    appId: '1:645043733402:ios:19e5955436bc0dfed9f023',
    messagingSenderId: '645043733402',
    projectId: 'health-arch-4b7c7',
    storageBucket: 'health-arch-4b7c7.appspot.com',
    iosClientId: '645043733402-ior2l8iqpajbainj5r925bni8vkaa1dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthArch.RunnerTests',
  );
}
